WebApplication1/Models/Guestbooks.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;


//此頁面負責與資料庫溝通

namespace WebApplication1.Models
{
    public class Guestbooks
    {
        // 編號
        [DisplayName("編號")]
        public int Id { get; set; }
       
        //帳號
        public string Account {  get; set; }
        // 名字
        [DisplayName("名字")]
        [Required(ErrorMessage ="請輸入名字")]
        [StringLength(20,ErrorMessage ="名字不可超過20個字元")]
        public string Name { get; set; }
        
        // 留言內容
        [DisplayName("留言內容")]
        [Required(ErrorMessage ="請輸入留言內容")]
        [StringLength(100,ErrorMessage ="留言內容不可超過100字元")]
        public string Content { get; set; }
        
        // 新增時間
        [DisplayName("新增時間")]
        public DateTime CreateTime { get; set; }
        
        // 回覆內容
        [DisplayName("回覆內容")]
        [StringLength(100,ErrorMessage ="回覆內容不可超過100字")]
        public string Reply { get; set; }

        // 回覆時間
        //DateTime? 資料型態，允許 DateTime 有 NULL 產生
        [DisplayName("回覆時間")]
        public DateTime? ReplyTime { get; set; }

        //會員 Member的外來鍵
        public Members Member { get; set; } = new Members();
    }
}

WebApplication1/ViewModels/GuestbooksViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using WebApplication1.Models;
using System.ComponentModel;
using WebApplication1.Services;


namespace WebApplication1.ViewModels
{
    public class GuestbooksViewModel
    {

        //搜尋欄位
        [DisplayName("搜尋：")]
        public string Search { get; set; }
        // 顯示資料陣列
        public List<Guestbooks> DataList { get; set; }

        //分頁內容
        public ForPaging Paging { get; set; }

    }
}

WebApplication1/Controllers/GuestbooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Mvc;
using System.Xml.Serialization;
using WebApplication1.Models;
using WebApplication1.Services;
using WebApplication1.ViewModels;

namespace WebApplication1.Controllers
{
    public class GuestbooksController : Controller
    {
        // GET: Guestbooks
        //宣告Guestbook資料表的Service物件
        //此物件為宣告一個名為GuestbookService物件 類別是在Service的GuestbooksDBService物件
        private readonly GuestbooksDBService GuestbookService = new GuestbooksDBService();
        public ActionResult Index()
        {
            return View();
        }

        //取得資料陣列用Action，將Page(頁數)預設為1
        public ActionResult GetDataList(string Search, int Page = 1)
        {
            //宣告一個新頁面模型
            GuestbooksViewModel Data = new GuestbooksViewModel();
            //將傳入值Search(搜尋)放入頁面模型中
            Data.Search = Search;
            //新增頁面模型中的分頁
            Data.Paging = new ForPaging(Page);
            //從Service中取得頁面所需陣列資料
            Data.DataList = GuestbookService.GetDataList(Data.Paging , Data.Search);
            //將頁面資料傳入View中
            return PartialView(Data);
        }
        [HttpPost]
        //設定搜尋為接受頁面POST傳入
        //使用Bind的Include來定義只接受的欄位，用來避免傳入其他不相干值
        public ActionResult GetDataList([Bind(Include = "Search")]GuestbooksViewModel Data)
        {
            //重新導向頁面至開始頁面，並傳入搜尋值
            return RedirectToAction("GetDataLsit" , new {Search = Data.Search});  
        }

        #region 新增留言
        //新增留言一開始載入頁面
        public ActionResult Create()
        {
            //因此頁面用於載入至開始頁面中，故使用部分檢視回傳
            return PartialView();
        }

        //設定留言時傳入資料的Action
        [Authorize] // 設定此 Action 須登入
        [HttpPost]
        //設定此Action只接受頁面POST資料傳入
        //使用Bind的Include來定義只接收的欄位，用來避免傳入其他不相干值
        public ActionResult Create([Bind(Include="Name,Content")]Guestbooks Data) 
        {
            //設定新增留言者為登入者
            Data.Account = User.Identity.Name;
            //使用service來新增一筆資料
            GuestbookService.IntertGuestbooks(Data);
            //重新導向面至開始頁面
            return RedirectToAction("Index");
        }
        #endregion

        #region 修改留言
        //新增留言頁面要根據傳入編號來決定要修改的資料
        [Authorize]//設定此Action需登入
        public ActionResult Edit(int Id)
        {
            //取得Service的資料
            Guestbooks Data = GuestbookService.GetDataByID(Id);

            //將資料傳入view中
            return View(Data);
        }
        //修改留言傳入資料的Action
        [Authorize]//設釘此Action需登入
        [HttpPost]//設定此Action只接受頁面POST資料傳入
        //使用Bind的Include來定義只接受的欄位，用來避免傳入其他不相干值
        public ActionResult Edit(int Id, [Bind(Include = "Name,Content")]Guestbooks UpdateData)
        {
            //修改資料的是否可修改判斷
            if(GuestbookService.CheckUpdate(Id))
            {
                //將編號設定至修改資料中
                UpdateData.Id= Id;
                //設定修改留言的留言者為登入者
                UpdateData.Account= User.Identity.Name; 
                //使用Service來修改資料
                GuestbookService.UpdataGuestbooks(UpdateData);
                //重新導向頁面至開始頁面
                return RedirectToAction("Index");

            }
            else
            {
                //重新導向至開始頁面
                return RedirectToAction("Index");
            }
        }
        #endregion

        #region 回覆留言
        //回覆留言頁面要根據傳入編號來決定回復的資料
        [Authorize(Roles ="Admin")] // 此Action只有Admin角色才可使用
        public ActionResult Reply(int Id)
        {
            //取得頁面所需資料，藉由Service取得
            Guestbooks Data = GuestbookService.GetDataByID(Id);
            //將資料傳入View中;
            return View(Data);
        }
        //修改留言傳入資料時的Action
        [HttpPost]//設定此Action只接受頁面POST的資料傳入
        [Authorize(Roles = "Admin")] // 設定此 Action 只有 Admin 角色才可使用
        //使用Bind的Include來定義只接受的欄位，用來避免傳入其他不相干值
        public ActionResult Reply(int Id, [Bind(Include = "Reply.ReplyTime")]Guestbooks ReplyData)
        {
            //修改資料的是否可修改判斷
            if (GuestbookService.CheckUpdate(Id))
            {
                //將編號設定至回覆留言中
                ReplyData.Id= Id;
                //使用Service來回覆留言
                GuestbookService.ReplyGuestbooks(ReplyData);
                //重新導向頁面至開始頁面
                return RedirectToAction("Index");
            }
            else
            {
                //重新導向頁面至開始頁面
                return RedirectToAction("Index");
            }
        }

        #endregion

        #region 刪除留言
        //刪除頁面要根據傳入編號來刪除資料
        [Authorize(Roles = "Admin")] // 設定此 Action 只有 Admin 角色才可使用
        public ActionResult Delete(int Id)
        {
           GuestbookService.DeleteGuestbooks(Id);
            return RedirectToAction("Index");
        }
        #endregion
    }
}

WebApplication1/Views/Guestbooks/Create.cshtml
@model WebApplication1.Models.Guestbooks


@*建立新增資料庫的表單*@

@using (Html.BeginForm("Create", "Guestbooks"))
{
    <h3>新增留言</h3>
    <table>
        @*新增內容欄位區塊*@
        <tr>
            <td>
                @Html.LabelFor(model => model.Content)
            </td>
            <td>

                @Html.TextBoxFor(model => model.Content)
                @*當輸入值不符合設定才會出現*@
                @Html.ValidationMessageFor(model => model.Content)
            </td>
        </tr>
    </table>
    <input type="submit" value="新增留言" />
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/Views/Guestbooks/Edit.cshtml
@model WebApplication1.Models.Guestbooks

@{ 
    ViewBag.Title = "修改留言";
}

@*匯入驗證欄位所需的JavaScript*@
@section scripts
    {
    @Scripts.Render("~/bundles/jqueryval.js")
    }

@*建立修改欄位所需的表單*@
@using (Html.BeginForm())
{
    <h3>修改留言</h3>
    @*建立修改留言表格*@

    <table>
        <tr>
            <td>
                @Html.LabelFor(model => model.Content)
            </td>
            <td>
                @Html.TextBoxFor(model => model.Content)
                @Html.ValidationMessageFor(model =>model.Content)
            </td>
        </tr>
    </table>@*判斷是否有人回覆，如果無人回覆，即可修改，否則不可修改*@
if (Model.ReplyTime == null)
{
        <input type="submit" value"修改留言" />

}
else
{
        <text>此留言已回覆無法修改，請</text>
        @Html.ActionLink("返回列表","Index")
}

}

WebApplication1/Views/Guestbooks/GetDataList.cshtml
@model WebApplication1.ViewModels.GuestbooksViewModel

<div id="DataList">
    <h2>留言板</h2>
    @*建立搜尋留言用的表單(使用AjaxHelper，並設定取代Id為DataList部分)*@
    @using (Ajax.BeginForm("GetDataList", "Guestbooks",
        new AjaxOptions
        {
            InsertionMode = InsertionMode.Replace,UpdateTargetId = "DataList"
        }))
    {
        <table>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Search)
                </td>
                <td>
                    @Html.TextBoxFor(model => model.Search)
                </td>
                <td>
                    <input type="submit" value="搜尋" />
                </td>
            </tr>
        </table>
    }
    <table>
        @*如果資料庫中不是零筆記錄，則顯示資料，並列出新增、刪除與修改連結*@
        @if (!Model.DataList.Count.Equals(0))
        {
            foreach (var item in Model.DataList)
            {
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.DataList[0].Name)
                    </td>
                    <td>
                        @item.Member.Name
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.DataList[0].CreateTime)
                    </td>
                    <td>
                        @item.CreateTime
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.DataList[0].Content)
                    </td>
                    <td colspan="3">
                        @item.Content
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.DataList[0].Reply)
                    </td>
                    <td colspan="3">
                        @item.Reply
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.DataList[0].ReplyTime)
                    </td>
                    <td>
                        @item.ReplyTime
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        @Html.ActionLink(" 修改留言", "Edit", new { Id = item.Id })
                        @if (User.IsInRole("Admim"))
                        {
                            @Html.ActionLink(" 回覆留言", "Reply", new { Id = item.Id })
                            @Html.ActionLink("刪除留言", "Delete", new { Id = item.Id })
                        }

                    </td>
                </tr>
            }
        }
        @*如果資料庫中為零筆記錄，則印出"資料庫內查無資料"*@
        else
        {
            <tr>
                <td colspan="4">
                    資料庫內查無資料
                </td>
            </tr>
        }
        @*顯示頁數連結(使用AjaxHelper，並設定取代Id為DataList部分)*@
        <tr>
            <td>
                @*若所在頁數大於1，則顯示上一頁與最前頁的按鈕*@
                @if (Model.Paging.NowPage > 1)
                {
                    @Ajax.ActionLink("<<", "GetDataList"
                                    , new { Page = 1, Search = Model.Search } 
                                    , new AjaxOptions
                                    {
                                        InsertionMode = InsertionMode.Replace
                                        ,
                                        UpdateTargetId = "DataList"
                                    })
                    @Ajax.ActionLink("<","GetDataList" 
                                    , new{Page = Model.Paging.NowPage - 1,Search = Model.Search }
                                    , new AjaxOptions
                                    {
                                        InsertionMode = InsertionMode.Replace,
                                        UpdateTargetId = "DataLsit"
                                    })
                }
            </td>
            <td>
                @*顯示在當前頁數前後各五頁的頁數*@
                @for (var page = (Model.Paging.NowPage - 6); page < (Model.Paging.NowPage + 6); page++)
                {
                    if ((page > 0) && (page <= Model.Paging.MaxPage))
                    {
                        if (page == Model.Paging.NowPage)
                        {
                            <b>@page</b>
                        }
                        else
                        {
                           @Ajax.ActionLink(page.ToString(),"GetDataList"
                           ,new {Page = page , Search = Model.Search}
                            ,new AjaxOptions
                            {
                                InsertionMode =InsertionMode.Replace , UpdateTargetId = "DataList"
                            })
                        }
                    }
                }
            </td>
            <td>
                @*若當前所在頁數小於總頁數，則顯示下一頁與最後一頁的按鈕*@
                @if (Model.Paging.NowPage < Model.Paging.MaxPage)
                {
                    @Ajax.ActionLink(">","GetDataList"
                    , new {Page = Model.Paging.NowPage + 1,Search = Model.Search}
                    , new AjaxOptions
                    {
                        InsertionMode = InsertionMode.Replace ,
                        UpdateTargetId = "DataList"
                    })
                    @Ajax.ActionLink(">>","GetDataList" 
                    , new {Page = Model.Paging.MaxPage ,Search = Model.Search }
                    , new AjaxOptions
                    {
                        InsertionMode = InsertionMode.Replace ,
                        UpdateTargetId = "DataList"
                    })

                }
            </td>
        </tr>
    </table>
</div>

WebApplication1/Views/Guestbooks/Index.cshtml
@model WebApplication1.ViewModels.GuestbooksViewModel

@{
    ViewBag.Title = "Index";
}


<h2>Index</h2>

@Html.AntiForgeryToken()
@*載入新增留言頁面*@
<div id="CreateData">
    @Html.Action("Create")
</div>

@*載入資料陣列頁面*@
@Html.Action("GetDataList")

@*匯入驗證欄位所須的JavaScript*@
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}



<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication1/Views/Guestbooks/Reply.cshtml
@model WebApplication1.Models.Guestbooks

@{
    ViewBag.Title = "回覆留言";
}

@*建立回覆留言所需的表單*@

@using (Html.BeginForm())
{
    <h3>回覆留言</h3>
    @*建立留言所需表格*@
    <table>
        <tr>
            <td>
                @Html.LabelFor(model => model.Content)
            </td>
            <td>
                @Html.TextBoxFor(model => model.Content)
                @Html.ValidationMessageFor(model => model.Content)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.Reply)
            </td>
            <td>
                @Html.TextBoxFor(model => model.Reply)
                @Html.ValidationMessageFor(model => model.Reply)
            </td>
        </tr>
    </table>
    @*一則留言僅可回復一次，若未被回復，則顯示返回列表按鈕*@
    if (Model.ReplyTime == null)
    {
        <input type="submit" value="回覆留言" />
    }
    else
    {
        <text>此則留言已回覆，請</text>
        @Html.ActionLink("返回列表", "Index")
    }
    @*匯入驗證所須的JavaScript*@
    @section scripts
 {
        @Scripts.Render("~/bundles/jqueryval.js")
    }

}